// frontend/src/pages/home/components/Header.tsx
import React, { useEffect, useState } from 'react';
import logo from '../../../assets/icons/app_white_24dp.svg';
import { getUser } from '../../../services/auth';
import { getLatencyInMillis } from '../../../services/bot';
import { User } from '../../../services/model/user';
import './Header.scss';

export function Header() {

  const [user, setUser] = useState<User>();
  const [latency, setLatency] = useState<number>();

  useEffect(() => {

    const fetchUser = async () => {
      const user = await getUser();
      setUser(user);
    };

    const fetchLatency = async () => {
      const latency = await getLatencyInMillis();
      setLatency(latency);
    };

    fetchUser();
    fetchLatency();
    setInterval(() => fetchLatency(), 5000);
  }, []);

  return (
    <div className="header">
      <img src={logo} alt="logo" className="logo"></img>
      <span>Discord Sound Board</span>
      <div className='user'>
        <div className='latency'>
          <div className='icon'></div>
          <div className='value'>{latency} ms</div>
        </div>
        <span><span className='thin'>Welcome, </span>{user?.username}</span>
        <img src={`https://cdn.discordapp.com/avatars/${user?.id}/${user?.avatar}.png`}></img>
      </div>
    </div>
  );
}

// frontend/src/routes/components/Header.svelte
<script lang="ts">
	import appIcon from '$lib/assets/icons/app_white_24dp.svg';
	import { onMount } from 'svelte';
	import { getLatency } from '$lib/api/bot.api';
	import User from './User.svelte';

	const LATENCY_POLL_INTERVAL_MS = 5000;

	let latency: number;
	onMount(async () => {
		const res = await getLatency();
		latency = res.latency;
		setInterval(async () => {
			const res = await getLatency();
			latency = res.latency;
		}, LATENCY_POLL_INTERVAL_MS);
	});
</script>

<div class="header bg-gradient-to-br from-purple-600 to-blue-500">
	<img src={appIcon} alt="logo" class="logo" />
	<span>Discord Sound Board</span>
	<div class="flex ml-auto justify-items-end">
		<div class="latency">
			<div class="icon" />
			<div class="value">{latency} ms</div>
		</div>
		<User />
		


	</div>
</div>

<style>
	.header {
		width: 100%;
		height: 100%;
		display: flex;
		align-items: center;
		gap: 16px;
		padding: 0 16px;
		color: white;
		box-sizing: border-box;
	}

	.logo {
		height: calc(100% - 12px);
	}

	.latency {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 6px;
	}

	.icon {
		width: 8px;
		height: 8px;
		background-color: rgb(0, 199, 0);
		border-radius: 99px;
	}

	.value {
		font-family: 'Roboto-Thin', sans-serif;
		font-size: 11px;
	}
</style>
